import { useState, useEffect } from 'react'
import { ShieldCheck, ShieldAlert, ShieldX, Info } from 'lucide-react'
import { getSafety } from '../api/client.js'
import ScoreRing from '../components/ScoreRing.jsx'
import StatusBadge from '../components/StatusBadge.jsx'
import LoadingSpinner from '../components/LoadingSpinner.jsx'
import ErrorState from '../components/ErrorState.jsx'

const SEV_ICON = {
  CRITICAL: ShieldX,
  HIGH:     ShieldAlert,
  MEDIUM:   ShieldAlert,
  LOW:      Info,
  NORMAL:   ShieldCheck,
}

const SEV_COLOR = {
  CRITICAL: 'text-red-400 bg-red-900/20 border-red-700/40',
  HIGH:     'text-red-400 bg-red-900/10 border-red-700/30',
  MEDIUM:   'text-amber-400 bg-amber-900/20 border-amber-700/40',
  LOW:      'text-amber-300 bg-amber-900/10 border-amber-700/20',
  NORMAL:   'text-green-400 bg-green-900/10 border-green-700/30',
}

export default function SafetyPage({ machineId }) {
  const [safety, setSafety] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError]   = useState(null)

  const load = async () => {
    setLoading(true); setError(null)
    try { setSafety(await getSafety(machineId)) }
    catch (e) { setError(e.message) }
    finally { setLoading(false) }
  }
  useEffect(() => { load() }, [machineId])

  if (loading) return <LoadingSpinner label="Evaluating Safety…" />
  if (error)   return <ErrorState message={error} onRetry={load} />

  const s = safety || {}
  const score = s.safety_score ?? 100
  const DecisionIcon = SEV_ICON[s.severity?.toUpperCase()] || ShieldCheck
  const decisionColor = SEV_COLOR[s.severity?.toUpperCase()] || SEV_COLOR.NORMAL

  return (
    <div className="space-y-6 max-w-5xl mx-auto">

      {/* ── Hero ───────────────────────────────────────────── */}
      <div className={`card border-l-4 ${score < 50 ? 'border-red-500' : score < 70 ? 'border-amber-500' : score < 85 ? 'border-amber-400' : 'border-green-500'}`}>
        <div className="flex items-center justify-between">
          <div>
            <div className="text-xs text-surface-100 uppercase tracking-wider mb-1">Safety Engine Decision</div>
            <div className="text-2xl font-bold text-white flex items-center gap-3">
              <DecisionIcon size={24} className={score < 50 ? 'text-red-400' : score < 70 ? 'text-amber-400' : 'text-green-400'} />
              {s.decision || 'NORMAL'}
            </div>
            <div className="mt-1 text-sm text-surface-100">{machineId}</div>
          </div>
          <ScoreRing score={score} size={96} label="Safety Score" />
        </div>
        <div className="mt-4 text-xs text-surface-200 bg-surface-600 rounded-lg px-3 py-2">
          ⓘ Safety decision generated by deterministic rule-based engine. Not AI-generated.
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">

        {/* Triggered Rules */}
        <div className="card space-y-3">
          <div className="section-title">Triggered Rules</div>
          {s.triggered_rules?.length ? s.triggered_rules.map((r, i) => {
            const Icon = SEV_ICON[r.severity] || Info
            const cls  = SEV_COLOR[r.severity] || SEV_COLOR.LOW
            return (
              <div key={i} className={`flex items-start gap-3 border rounded-lg p-3 ${cls}`}>
                <Icon size={16} className="mt-0.5 shrink-0" />
                <div className="text-sm">
                  <div className="font-semibold font-mono text-xs mb-0.5">{r.rule_id}</div>
                  <div>{r.description}</div>
                </div>
              </div>
            )
          }) : (
            <div className="flex items-center gap-2 text-green-400 text-sm">
              <ShieldCheck size={16} /> No rules triggered. All clear.
            </div>
          )}
        </div>

        {/* Recommendations */}
        <div className="card space-y-3">
          <div className="section-title">Recommendations</div>
          {s.recommendations?.length ? s.recommendations.map((r, i) => (
            <div key={i} className="flex items-start gap-2 text-sm text-gray-300">
              <span className="text-cat-500 shrink-0 font-bold">{i + 1}.</span>
              <span>{r}</span>
            </div>
          )) : (
            <div className="text-sm text-surface-100">No recommendations at this time.</div>
          )}
        </div>
      </div>

      {/* Signal summary */}
      <div className="card">
        <div className="section-title">Safety Signals</div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <Signal label="Seatbelt"        value={s.seatbelt_status} bad={s.seatbelt_status === 'Unfastened'} />
          <Signal label="Safety Alert"    value={s.safety_alert}    bad={s.safety_alert === 'Yes'} />
          <Signal label="Behavior"        value={s.behavior_anomaly ? 'ANOMALY' : 'NORMAL'} bad={s.behavior_anomaly} />
          <Signal label="Weather"         value={s.weather_condition} bad={['Rainy','Stormy','Windy'].includes(s.weather_condition)} />
        </div>
      </div>

      {/* Score breakdown */}
      <div className="card">
        <div className="section-title">Score Thresholds</div>
        <div className="grid grid-cols-4 gap-3 text-center text-sm">
          {[
            { label: 'NORMAL',     range: '85–100', color: 'text-green-400' },
            { label: 'CAUTION',    range: '70–84',  color: 'text-amber-400' },
            { label: 'CHECK',      range: '50–69',  color: 'text-orange-400' },
            { label: 'STOP',       range: '< 50',   color: 'text-red-400' },
          ].map(t => (
            <div key={t.label} className={`rounded-lg p-3 border ${score >= parseInt(t.range) ? 'border-surface-400 bg-surface-600' : 'border-surface-600'}`}>
              <div className={`font-bold ${t.color}`}>{t.label}</div>
              <div className="text-xs text-surface-100 mt-0.5">{t.range}</div>
            </div>
          ))}
        </div>
        <div className="mt-3 text-xs text-surface-100">
          Current score: <span className="text-cat-500 font-bold">{score}</span>
        </div>
      </div>
    </div>
  )
}

function Signal({ label, value, bad }) {
  return (
    <div className={`rounded-lg p-3 border text-center ${bad ? 'border-red-700/50 bg-red-900/10' : 'border-surface-500 bg-surface-600'}`}>
      <div className="text-xs text-surface-100 mb-1">{label}</div>
      <div className={`font-semibold text-sm ${bad ? 'text-red-400' : 'text-green-400'}`}>{value ?? '—'}</div>
    </div>
  )
}
